export const endpoints = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    profile: '/auth/profile',
  },
  market: {
    stocks: '/market/stocks',
    availableStocks: '/market/available-stocks',
    stock: (symbol: string) => `/market/stocks/${symbol}`,
    quote: (symbol: string) => `/market/quote/${symbol}`,
    quotes: '/market/quotes',
    profile: (symbol: string) => `/market/profile/${symbol}`,
    crypto: '/market/crypto',
    trendingCrypto: '/market/crypto/trending',
    mutualFunds: '/market/mutual-funds',
    trending: '/market/trending',
    gainers: '/market/gainers',
    losers: '/market/losers',
    history: (symbol: string) => `/market/history/${symbol}`,
    news: '/market/news',
    trends: '/market/trends',
    sentiment: '/market/sentiment',
    aiInsights: '/market/ai-insights',
  },
  ai: {
    summary: '/ai/summary',
    insights: '/ai/insights',
    risk: '/ai/risk',
    suggestions: '/ai/suggestions',
    newsSentiment: '/ai/news-sentiment',
    marketTrends: '/ai/market-trends',
    transactions: '/ai/transactions',
    chat: '/ai/chat',
  },
  dashboard: {
    summary: '/dashboard/summary',
  },
  portfolio: {
    root: '/portfolio',
    analytics: '/portfolio/analytics',
    buy: '/portfolio/buy',
    sell: '/portfolio/sell',
    transactions: '/portfolio/transactions',
    profitLoss: '/portfolio/profit-loss',
    holdings: '/portfolio/holdings',
    holding: (holdingId: string) => `/portfolio/holdings/${holdingId}`,
  },
  transactions: {
    root: '/transactions',
    monthly: '/transactions/monthly',
    summary: '/transactions/summary',
    analytics: '/transactions/analytics',
    buy: '/transactions/buy',
    sell: '/transactions/sell',
    detail: (transactionId: string) => `/transactions/${transactionId}`,
  },
  watchlist: {
    root: '/watchlist',
    symbol: (symbol: string) => `/watchlist/${symbol}`,
  },
  watchlists: {
    root: '/watchlists',
    detail: (watchlistId: string) => `/watchlists/${watchlistId}`,
    items: (watchlistId: string) => `/watchlists/${watchlistId}/items`,
    item: (watchlistId: string, symbol: string) => `/watchlists/${watchlistId}/items/${symbol}`,
  },
  settings: {
    root: '/settings',
    profile: '/settings/profile',
    preferences: '/settings/preferences',
  },
};
